package environment

const (
	OPENSEARCH_ENDPOINT  = "OPENSEARCH_ENDPOINT"
	OPENSEARCH_MAX_RETRY = "OPENSEARCH_MAX_RETRY"
	OPENSEARCH_PASSWORD  = "OPENSEARCH_PASSWORD"
	OPENSEARCH_PROFILE   = "OPENSEARCH_PROFILE"
	OPENSEARCH_TIMEOUT   = "OPENSEARCH_TIMEOUT"
	OPENSEARCH_USER      = "OPENSEARCH_USER"
)
