#!/bin/bash

# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
#
# Modifications Copyright OpenSearch Contributors. See
# GitHub history for details.

#Custermize this for your application
APPLICATION_FILE_PATH=opensearch-cli

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcut to /usr/local/bin
rm -f /usr/local/bin/opensearch-cli
ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/opensearch-cli
echo "Post installation process finished"
