name: Integration with Unreleased OpenSearch
on:
  push:
    branches:
      - main
      - opensearch-*
  pull_request:
    branches:
      - main
      - opensearch-*
env:
  OPENSEARCH_VERSION: '2.x'

jobs:
  integ-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 11 ]
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout OpenSearch
        uses: actions/checkout@v3
        with:
          repository: opensearch-project/opensearch
          ref: ${{ env.OPENSEARCH_VERSION }}
          path: opensearch

      - name: Assemble OpenSearch
        run: |
          cd opensearch
          ./gradlew assemble
        # This step runs the docker image generated during gradle assemble in OpenSearch. It is tagged as opensearch:test.
        # Reference: https://github.com/opensearch-project/OpenSearch/blob/2.0/distribution/docker/build.gradle#L190
      - name: Run Docker Image
        run: |
          docker run -p 9200:9200 -p 9600:9600 -d -e "discovery.type=single-node" -e "bootstrap.memory_lock=true" opensearch:test
          sleep 90

      - name: Set up Go ubuntu-latest
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.2

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Run Integration Tests
        env:
          GOPROXY: "https://proxy.golang.org"
          OPENSEARCH_ENDPOINT: "http://localhost:9200"
        run: make test.integration.insecure
